-- Р“Р»Р°РІРЅРѕРµ РјРµРЅСЋ РґР»СЏ РўРµРЅРµР№ Р§РµСЂРЅРѕР±С‹Р»СЏ.
-- KRodin (c) 2018
-- Р’С‹РєРёРЅСѓР» РёР· СЃРєСЂРёРїС‚Р° РІСЃС‘ С‡С‚Рѕ СЃРІСЏР·Р°РЅРѕ СЃ РјСѓР»СЊС‚РёРїР»РµРµСЂРѕРј Рё РїСЂРѕС‡РёР№ РјСѓСЃРѕСЂ.
-- РСЃРїСЂР°РІРёР» СѓС‚РµС‡РєРё РїР°РјСЏС‚Рё РёР·-Р·Р° РЅРµСѓРґР°Р»РµРЅРёСЏ С‡Р°СЃС‚РµР№ РјРµРЅСЋ РїРѕСЃР»Рµ РµРіРѕ Р·Р°РєСЂС‹С‚РёСЏ (СЃРј. main_menu:close_and_delete_menu())
-- РЎРґРµР»Р°РЅРѕ СЃРїРµС†РёР°Р»СЊРЅРѕ РґР»СЏ РёСЃРїРѕР»СЊР·РѕРІР°РЅРёСЏ СЃ РґРІРёР¶РєРѕРј OGSR.

class "main_menu" (CUIScriptWnd)

function main_menu:__init() super()
	self.mbox_mode = 0
	self:InitControls()
	self:InitCallBacks()
   mm = _G.main_menu.get_main_menu()
end

function main_menu:__finalize()

end

function main_menu:InitControls()
	self:Init(0,0,1024,768)			  
	local xml = CScriptXmlInit()
	xml:ParseFile("ui_mm_main.xml")
	xml:InitStatic("background", self)
	xml:InitStatic("rad_vignette", self)
	xml:InitStatic("Golden_sphere_shadow_img", self)
	xml:InitStatic("sfz_logo_img", self)
	xml:InitStatic("fire_movie", self)
        self.shniaga = xml:InitMMShniaga("shniaga_wnd",self)
	
	self:Register(xml:Init3tButton("new_game", self),"new_game")
	self:Register(xml:Init3tButton("load_game", self),"load_game")
	self:Register(xml:Init3tButton("load_last_save", self),"load_last_save")
	if level.present() and (db.actor ~= nil) and db.actor:alive() then
	self:Register(xml:Init3tButton("save_game", self),"save_game")
	end
	self:Register(xml:Init3tButton("options_game", self),"options_game")
	self:Register(xml:Init3tButton("quit_game", self),"quit_game")
	
	self:Register(xml:Init3tButton("easy", self), "easy")
	self:Register(xml:Init3tButton("medium", self), "medium")
	self:Register(xml:Init3tButton("hard", self), "hard")
	self:Register(xml:Init3tButton("very_hard", self), "very_hard")
	self:Register(xml:Init3tButton("back", self), "back")
	
	self:Register(xml:InitStatic("legal_info_statement", self), "legal_info_statement")
	self:Register(xml:Init3tButton("back_legal", self), "back_legal")
	self:Register(xml:Init3tButton("legal_info", self), "legal_info")
	self:Register(xml:Init3tButton("legal_steam_link", self), "legal_steam_link")
	self:Register(xml:Init3tButton("legal_gog_link", self), "legal_gog_link")
	self:Register(xml:Init3tButton("legal_playstation_link", self), "legal_playstation_link")
	self:Register(xml:Init3tButton("legal_xbox_link", self), "legal_xbox_link")

	self:ToggleDifficultyButtons(false)
	self:ToggleLegalInfo(false)

	self.message_box = CUIMessageBoxEx()
	self:Register(self.message_box, "msg_box")	

	xml:InitStatic("ogsm_version",   self):SetText("Mod version: " .. sys_ini:r_string_wq("mod_ver", "mod_ver"))
	xml:InitStatic("static_version", self):SetText("Engine version: " .. _G.main_menu.get_main_menu():GetGSVer())
	
	if rad_dev_mode.is_developer_mode() then
        xml:InitStatic("dev_mode", self)
    end
end

function main_menu:Show(...)
	self.shniaga:SetVisibleMagnifier(...)
end


function main_menu:InitCallBacks()
		
self:AddCallback("new_game", ui_events.BUTTON_CLICKED, self.OnButton_start_new_game, self)
self:AddCallback("load_game", ui_events.BUTTON_CLICKED,	self.OnButton_load_clicked, self)
self:AddCallback("load_last_save", ui_events.BUTTON_CLICKED,	self.OnButton_last_save, self)
self:AddCallback("save_game", ui_events.BUTTON_CLICKED,	self.OnButton_save_clicked, self)
self:AddCallback("options_game", ui_events.BUTTON_CLICKED, self.OnButton_options_clicked, self)
self:AddCallback("quit_game", ui_events.BUTTON_CLICKED,	self.OnButton_quit_clicked, self)
self:AddCallback("legal_info", ui_events.BUTTON_CLICKED,	self.OnButton_legal_info_clicked, self)
self:AddCallback("back_legal", ui_events.BUTTON_CLICKED, self.OnButton_back_legal_clicked, self)
self:AddCallback("legal_steam_link", ui_events.BUTTON_CLICKED, self.OnButton_legal_steam_link_clicked, self)
self:AddCallback("legal_gog_link", ui_events.BUTTON_CLICKED, self.OnButton_legal_gog_link_clicked, self)
self:AddCallback("legal_playstation_link", ui_events.BUTTON_CLICKED, self.OnButton_legal_playstation_link_clicked, self)
self:AddCallback("legal_xbox_link", ui_events.BUTTON_CLICKED, self.OnButton_legal_xbox_link_clicked, self)

self:AddCallback("easy", ui_events.BUTTON_CLICKED, function() self:StartGame(1) end, self)
self:AddCallback("medium", ui_events.BUTTON_CLICKED, function() self:StartGame(2) end, self)
self:AddCallback("hard", ui_events.BUTTON_CLICKED, function() self:StartGame(3) end, self)
self:AddCallback("very_hard", ui_events.BUTTON_CLICKED, function() self:StartGame(4) end, self)
self:AddCallback("back", ui_events.BUTTON_CLICKED, self.OnButton_cancel_new_game, self)

	
self:AddCallback("btn_quit_to_mm", ui_events.BUTTON_CLICKED, self.OnButton_disconnect_clicked, self)
self:AddCallback("btn_ret", ui_events.BUTTON_CLICKED, self.OnButton_return_game, self)
self:AddCallback("btn_lastsave", ui_events.BUTTON_CLICKED, self.OnButton_last_save, self)
self:AddCallback("btn_credits",	ui_events.BUTTON_CLICKED, self.OnButton_credits_clicked, self)
	-- message box																										
	self:AddCallback("msg_box",     ui_events.MESSAGE_BOX_OK_CLICKED,		self.OnMsgOk,						self)
	self:AddCallback("msg_box",     ui_events.MESSAGE_BOX_CANCEL_CLICKED,	self.OnMsgCancel,					self)
	self:AddCallback("msg_box",     ui_events.MESSAGE_BOX_YES_CLICKED,		self.OnMsgYes,						self)
	self:AddCallback("msg_box",     ui_events.MESSAGE_BOX_NO_CLICKED,		self.OnMsgNo,						self)
	self:AddCallback("msg_box",			ui_events.MESSAGE_BOX_QUIT_GAME_CLICKED,self.OnMessageQuitGame,				self)
	self:AddCallback("msg_box",			ui_events.MESSAGE_BOX_QUIT_WIN_CLICKED,	self.OnMessageQuitWin,				self)
end

function main_menu:OnButton_legal_steam_link_clicked()
	os.execute('start "" ' .. "https://store.steampowered.com/franchise/stalker")
end

function main_menu:OnButton_legal_gog_link_clicked()
	os.execute('start "" ' .. "https://www.gog.com/en/game/stalker_shadow_of_chernobyl")
end

function main_menu:OnButton_legal_playstation_link_clicked()
	os.execute('start "" ' .. "https://store.playstation.com/en-cz/product/EB0236-CUSA43978_00-0550328121149114")
end

function main_menu:OnButton_legal_xbox_link_clicked()
	os.execute('start "" ' .. "https://www.xbox.com/en-US/games/store/stalker-legends-of-the-zone-trilogy/9N4GFFDG41JR")
end

function main_menu:OnButton_start_new_game()
    self:ToggleMainButtons(false)
    self:ToggleDifficultyButtons(true)
end

function main_menu:OnButton_cancel_new_game()
    self:ToggleMainButtons(true)
    self:ToggleDifficultyButtons(false)
end

function main_menu:ToggleDifficultyButtons(value)
    local buttons = {"easy", "medium", "hard", "very_hard", "back"}
    for _, button_name in ipairs(buttons) do
        local btn = self:GetButton(button_name)
        if btn then
            btn:Show(value)
        end
    end
end

function main_menu:OnMsgOk()
	self.mbox_mode = 0
end

function main_menu:OnMsgCancel()
	self.mbox_mode = 0
	PlaySound("mod\\mainmenu_button_cancel_sound")
end

function main_menu:LoadLastSave()
	cmd("load_last_save")
	self:close_and_delete_menu()
end

function main_menu:OnMsgYes()
	if self.mbox_mode == 1 then
		self:LoadLastSave()	
	end


	

	self.mbox_mode = 0
end

function main_menu:OnMsgNo()
	self.mbox_mode = 0

end

function main_menu:OnButton_last_save()
	if not level.present() or not ( db.actor_proxy.online and db.actor:alive() ) then
		self:LoadLastSave()
		return
	end

	self.mbox_mode = 1
	self.message_box:Init("message_box_confirm_load_save")
	self:GetHolder():start_stop_menu(self.message_box, true)
end

function main_menu:OnButton_credits_clicked()
	game.start_tutorial("credits_seq")
end

function main_menu:OnButton_quit_clicked()
	self.message_box:Init("message_box_quit_windows")
	self:GetHolder():start_stop_menu(self.message_box, true)
end

function main_menu:OnButton_back_legal_clicked()
	self:ToggleMainButtons(true)
	self:ToggleLegalInfo(false)
end

function main_menu:OnButton_legal_info_clicked()
	self:ToggleMainButtons(false)
	self:ToggleLegalInfo(true)
end

function main_menu:ToggleMainButtons(value)
	local buttons = {
        "new_game", "load_game", "load_last_save", "save_game", "options_game", "quit_game", "legal_info"
    }
    for _, button_name in ipairs(buttons) do
        local btn = self:GetButton(button_name)
        if btn then
            btn:Show(value)
        end
    end
end

function main_menu:ToggleLegalInfo(value)
	local legal_info_statement = self:GetStatic("legal_info_statement")
	if legal_info_statement then
		legal_info_statement:Show(value)
	end
	
	local buttons = {
        "legal_steam_link", "back_legal", "legal_gog_link", "legal_playstation_link", "legal_xbox_link"
    }
    for _, button_name in ipairs(buttons) do
        local btn = self:GetButton(button_name)
        if btn then
            btn:Show(value)
        end
    end
end

function main_menu:OnButton_disconnect_clicked()
	self.message_box:Init("message_box_quit_game")
	self.message_box:SetText("ui_mm_quit_game_message")
	self:GetHolder():start_stop_menu(self.message_box, true)
end

function main_menu:OnMessageQuitGame()
	local console = get_console()
	console:execute("disconnect")
end

function main_menu:OnMessageQuitWin()
	local console = get_console()
	console:execute("quit")
end

function main_menu:OnButton_return_game()
	local console = get_console()
	console:execute("main_menu off")
end

function main_menu:OnButton_load_spawn()
	if not self.spawn_dlg then
		self.spawn_dlg = ui_si.spawn_item_dialog()
		self.spawn_dlg.owner = self
	end
	self:GetHolder():start_stop_menu(self.spawn_dlg, true)
	self:Show(false)
end

function check_game()
	return level.present() and db.actor and db.actor:alive()
end

function main_menu:StartGame( diff_id )
	get_console():execute("g_rad3_game_diff gdiff_" .. diff_id)
	get_console():execute("g_rad3_economy_diff econ_" .. diff_id)
	if alife() then
		cmd("disconnect")	
	end
	cmd("start server(all/single/alife/new)")
	self:close_and_delete_menu()
end

function main_menu:OnButton_save_clicked()
	if not self.save_dlg then
		self.save_dlg = ui_mm_save_load_dialog.save_load_dialog( true )
		self.save_dlg.owner = self
	end
	--
	ui_mm_save_load_dialog.fill_savedgames_list(self.save_dlg)
	--
	self:GetHolder():start_stop_menu(self.save_dlg, true)
	self:Show(false)
end

function main_menu:OnButton_load_clicked()
	if not self.load_dlg then
		self.load_dlg = ui_mm_save_load_dialog.save_load_dialog()
		self.load_dlg.owner = self
	end
	--
	ui_mm_save_load_dialog.fill_savedgames_list(self.load_dlg)
	--
	self:GetHolder():start_stop_menu(self.load_dlg, true)
	self:Show(false)
end

function main_menu:OnButton_options_clicked()
	if not self.opt_dlg then
		self.opt_dlg = ui_mm_opt_main.options_dialog()
		self.opt_dlg.owner = self
	end

	self:GetHolder():start_stop_menu(self.opt_dlg, true)
	self:Show(false)
end

function main_menu:OnKeyboard(dik, keyboard_action)  --virtual function

	CUIScriptWnd.OnKeyboard(self,dik,keyboard_action)

	local bind = dik_to_bind(dik)
	local console = get_console()

	if keyboard_action == ui_events.WINDOW_KEY_PRESSED then
		if dik_to_bind(dik) == key_bindings.kQUIT then
			if level.present() and db.actor and db.actor:alive() then
				ogse_signals.get_mgr():call( "on_mm_return_game" )
				self:close_and_delete_menu()
			end
		end

		if dik == DIK_keys.DIK_Q then
		    local console = get_console()
		    console:execute("quit")
		end  
  
		if rad_dev_mode.is_developer_mode() then
			if dik == DIK_keys.DIK_NUMPAD3 then
					acc_time()
			elseif dik == DIK_keys.DIK_NUMPAD2 then
					ret_time()
			elseif dik == DIK_keys.DIK_NUMPAD1 then
					dec_time()
			elseif dik == DIK_keys.DIK_C then
				if db.actor then
					coordinates_to_console_and_log()
					console:execute("main_menu off")
				end
			elseif dik == DIK_keys.DIK_P then --SDATA
				if ogse.check_game() then
					if not _sdata.GlobalEnable then
						_sdata.subscribe()
					else
						_sdata.unsubscribe()
					end
				end
			elseif dik == DIK_keys.DIK_K then
				if db.actor then
					rad_funcs.find_all_seekers()
					console:execute("main_menu off")
				end
			end
		end

		return true
	end
   
	return false
end


--Для закрытия меню использовать только этот специальный метод!
function main_menu:close_and_delete_menu()
	-- Удаляем в движке каллбеки, в которых хранятся ссылки на объекты оконных классов (которые добавляются в AddCallback(..., self),
	-- иначе части меню не удалятся и будут висеть в памяти до перезапуска LUA (до загрузки сейва, например)
	-- Так же, надо обнулить висячие ссылки (self.*_dlg), иначе сборщик мусора эти объекты не удалит. Да, это странно, но это так.
	if self.save_dlg then self.save_dlg:ClearCallbacks() self.save_dlg = nil end
	if self.load_dlg then self.load_dlg:ClearCallbacks() self.load_dlg = nil end
	if self.opt_dlg then
		if self.opt_dlg.dlg_video_adv then self.opt_dlg.dlg_video_adv = nil end
		self.opt_dlg:ClearCallbacks() self.opt_dlg = nil
	end
	if self.spawn_dlg then self.spawn_dlg:ClearCallbacks() self.spawn_dlg = nil end
	self:ClearCallbacks() --main_menu СѓРґР°Р»СЏРµС‚СЃСЏ РґРІРёР¶РєРѕРј, РЅРѕ РґР»СЏ РЅР°РґС‘Р¶РЅРѕСЃС‚Рё Рё РµРјСѓ РєР°Р»Р»Р±РµРєРё СѓРґР°Р»РёРј.
	--
	cmd("main_menu off")

end

function main_menu:TestBlowout()
	xr_logic.pstor_store(db.actor, "blowout", true)
end

local k = 1000

function acc_time()
	local t = xr_logic.pstor_retrieve(db.actor, "t", 0)
	t = t + k
	level.set_time_factor(t)
	xr_logic.pstor_store(db.actor, "t", t)
	rad_respawn.periodic_spawn()
	news_manager.send_tip(db.actor, "%c[25,240,25,25]Timefactor increased to "..t.."", nil, nil, 20000)
end

function ret_time()
	level.set_time_factor(10)
	xr_logic.pstor_store(db.actor, "t", 0)
	news_manager.send_tip(db.actor, "%c[0,0,255,25]Timefactor set to default (10)", nil, nil, 20000)
end

function dec_time()
	local t = xr_logic.pstor_retrieve(db.actor, "t", 0)
	t = t - k
	if t <= 0 then
		ret_time()
	else
		level.set_time_factor (t)
		xr_logic.pstor_store(db.actor, "t", t)
		news_manager.send_tip(db.actor, "%c[255,240,155,25]Timefactor reduced to "..t.."", nil, nil, 20000)
	end	
end

function main_menu:start_atlas(action)

if level.present() and (db.actor ~= nil) and db.actor:alive() then
	get_console():execute("main_menu off")
    	local target = ui_atlas.atlas(get_hud(),action)
    	level.start_stop_menu(target, true)
	end

end

function coordinates_to_console_and_log()
	-- Put a message about our location into the console and log file
	local a    = db.actor:position()        -- Our position's coordinates
	local lvid  = db.actor:level_vertex_id() 
	local gvid = db.actor:game_vertex_id() 
	--local text = level.name().."#XYZ:"..tostring(a.x)..","..tostring(a.y)..","..tostring(a.z).."#Lvid:"..tostring(lvid).."#Gvid:"..tostring(gvid)
	local text = "{vector():set(" .. tostring(a.x) .. ", " .. tostring(a.y) .. ", " .. tostring(a.z) .. "), " .. tostring(lvid) .. ", " .. tostring(gvid) .. "}"
	log3(text)
end

prefetch('add_cheat_spawn')